# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"medium_publications": "Loading RSS Feeds.ipynb",
         "medium_url_template": "Loading RSS Feeds.ipynb",
         "medium_url": "Loading RSS Feeds.ipynb",
         "medium_urls": "Loading RSS Feeds.ipynb",
         "subreddits": "Loading RSS Feeds.ipynb",
         "reddit_url_template": "Loading RSS Feeds.ipynb",
         "reddit_url": "Loading RSS Feeds.ipynb",
         "reddit_urls": "Loading RSS Feeds.ipynb",
         "get_article_text": "Loading RSS Feeds.ipynb",
         "get_feed_article_texts": "Loading RSS Feeds.ipynb",
         "get_feed_article_df": "Loading RSS Feeds.ipynb",
         "add_field": "Loading RSS Feeds.ipynb",
         "paperswithcode_url": "Loading RSS Feeds.ipynb",
         "hackernews_url": "Loading RSS Feeds.ipynb",
         "rss_feed_urls": "Loading RSS Feeds.ipynb",
         "to_date": "Loading RSS Feeds.ipynb",
         "get_feed_df": "Zero-shot Classification of RSS Feeds.ipynb",
         "Searcher": "Searching RSS feeds with haystack.ipynb",
         "topic_strings": "Zero-shot Classification of RSS Feeds.ipynb",
         "get_zero_shot_classification_results": "Zero-shot Classification of RSS Feeds.ipynb",
         "get_zero_shot_classification_results_df": "Zero-shot Classification of RSS Feeds.ipynb"}

modules = ["rss_feeds.py",
           "haystack_search.py",
           "zero_shot_learning.py"]

doc_url = "https://fastai.github.io/pytorch_hackathon/"

git_url = "https://github.com/fastai/pytorch_hackathon/tree/master/"

def custom_doc_links(name): return None
